# This file contains values from Cookiecutter

default_context:
  project_name: "fast-ensemble"
  project_description: "Ensemble capabilities on top of fastai."
  organization: "Tomas Ambrogi"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "tomiambro"
  email: "tomi.ambro94@gmail.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "none"
